language: php
cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - '7.2'
  - '7.3'
  - '7.4'

env:
  - LARAVEL=5.5 TEST_DB_ENGINE=sqlite
  - LARAVEL=5.5 TEST_DB_ENGINE=mysql
  - LARAVEL=5.5 TEST_DB_ENGINE=pgsql
  - LARAVEL=5.6 TEST_DB_ENGINE=sqlite
  - LARAVEL=5.6 TEST_DB_ENGINE=mysql
  - LARAVEL=5.6 TEST_DB_ENGINE=pgsql
  - LARAVEL=5.7 TEST_DB_ENGINE=sqlite
  - LARAVEL=5.7 TEST_DB_ENGINE=pgsql
  - LARAVEL=5.7 TEST_DB_ENGINE=mysql
  - LARAVEL=5.8 TEST_DB_ENGINE=sqlite
  - LARAVEL=5.8 TEST_DB_ENGINE=mysql
  - LARAVEL=5.8 TEST_DB_ENGINE=pgsql
  - LARAVEL=6.0 TEST_DB_ENGINE=sqlite
  - LARAVEL=6.0 TEST_DB_ENGINE=mysql
  - LARAVEL=6.0 TEST_DB_ENGINE=pgsql
  - LARAVEL=6.18 TEST_DB_ENGINE=sqlite
  - LARAVEL=6.18 TEST_DB_ENGINE=mysql
  - LARAVEL=6.18 TEST_DB_ENGINE=pgsql
  - LARAVEL=7.0 TEST_DB_ENGINE=sqlite
  - LARAVEL=7.0 TEST_DB_ENGINE=mysql
  - LARAVEL=7.0 TEST_DB_ENGINE=pgsql
  - LARAVEL=7.28 TEST_DB_ENGINE=sqlite
  - LARAVEL=7.28 TEST_DB_ENGINE=mysql
  - LARAVEL=7.28 TEST_DB_ENGINE=pgsql
  - LARAVEL=8.0 TEST_DB_ENGINE=sqlite
  - LARAVEL=8.0 TEST_DB_ENGINE=mysql
  - LARAVEL=8.0 TEST_DB_ENGINE=pgsql
  - LARAVEL=8.1 TEST_DB_ENGINE=sqlite
  - LARAVEL=8.1 TEST_DB_ENGINE=mysql
  - LARAVEL=8.1 TEST_DB_ENGINE=pgsql

matrix:
  exclude:
    - php: '7.2'
      env: 'LARAVEL=8.0 TEST_DB_ENGINE=sqlite'
    - php: '7.2'
      env: 'LARAVEL=8.0 TEST_DB_ENGINE=mysql'
    - php: '7.2'
      env: 'LARAVEL=8.0 TEST_DB_ENGINE=pgsql'
    - php: '7.2'
      env: 'LARAVEL=8.1 TEST_DB_ENGINE=sqlite'
    - php: '7.2'
      env: 'LARAVEL=8.1 TEST_DB_ENGINE=mysql'
    - php: '7.2'
      env: 'LARAVEL=8.1 TEST_DB_ENGINE=pgsql'

script:
  - vendor/bin/phpunit --testdox
before_install:
  - MINOR=`echo $LARAVEL | sed 's/[5|6|7|8]\.\([0-9]\+\)/\1/'`
  - '[[ $LARAVEL =~ ^6\.[0-9]+$ ]] && MAJOR=6 || MAJOR=5'
  - '[[ $LARAVEL =~ ^7\.[0-9]+$ ]] && MAJOR=7 || true'
  - '[[ $LARAVEL =~ ^8\.[0-9]+$ ]] && MAJOR=8 || true'
  - echo "Testing against Laravel ${MAJOR}.${MINOR}"
  - composer require "illuminate/support:${MAJOR}.${MINOR}.*" --no-update -v
  - composer require "illuminate/console:${MAJOR}.${MINOR}.*" --no-update -v
  - sh -c "[ ! -z $TEST_DB_ENGINE ] && [ 'mysql' = $TEST_DB_ENGINE ] && mysql -e 'DROP DATABASE IF EXISTS migration_compat_test;CREATE DATABASE migration_compat_test;'" || true
  - sh -c "[ ! -z $TEST_DB_ENGINE ] && [ 'pgsql' = $TEST_DB_ENGINE ] && psql -c 'create database migration_compat_test;' -U postgres" || true
install: composer install --no-interaction
services:
  - mysql
  - postgresql
notifications:
  email: false
  slack:
    secure: "ffc5qcn9X/K/bXR3xdw50Vxm8IzEMaV0xt/VLgcrLg18syOwdKHks7zKxtzxej9QQKRxPT26A4sLr4UOv6tB145Ek357jX/chdb34J1jokW0YAjdJDpwh5w/PrhLLoOwPV/Ppem+/AiQmMXgOILb2F/JiR3LIfoKy2DGIb9jWxxCudwjO4yMixHGDC0SPQ5NOtUXFkc47Qd0/0DZNBvsdaYoj82XHANQPwS/F8oT1uX3gGzHA1C94n0xSLNVk0UeA7nieWrkrE9EKtyYHA5reI1q6YmM1MAl2lYHqQhu4PDTHzVA/xS0YwvEpmIK3FH3Nd/kOzaDRkpTziQnHHYyqxx3tssCgAR8cxWEfuyjiyRPhlWsC3YCZL5gPPWX83sjznWgLKPXO0XMPtW1W+iFB953c+VuvaEIKoxAH/NL5yuJVllQXMsDsgZLNqAt//7ENm692NtvcVk0ksPyjYP4+rmszy1k1/B8l8uRHg9ceNuHdaASXFokd6y6l2riWqhNtfClv+/SwjxP5nFGAlDFKrH1PSfr5kDTnM0XuVfn87ILQFpIEX7WFifOGP3NraFLAMKfscA8nBd4cv/qHz28fs3FH17IRF0rnMMpab17S9fzUsM1Vi6XDXzbvSGFNEOJdr2kvTIKOMu4dewBUH2kHxXB7qb9WRoP/3Z1fkPkq68="
