name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        php: ['7.3', '7.4', '8.0']
        laravel: ['6.0', '6.20', '7.0', '7.30', '8.0', '8.19']
        dbengine: ['sqlite', 'mysql']
        exclude:
          - php: '8.0'
            laravel: '6.0'
          - php: '8.0'
            laravel: '7.0'
          - php: '8.0'
            laravel: '8.0'
    name: PHP ${{ matrix.php }} Laravel ${{ matrix.laravel }} [${{ matrix.dbengine }}]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, json, sqlite3
          tools: composer:v2
      - name: Lock Laravel Version
        run: composer require "illuminate/support:${{ matrix.laravel }}.*" --no-update -v && composer require "illuminate/console:${{ matrix.laravel }}.*" --no-update -v
      - name: Composer Install
        run: composer install --prefer-dist --no-progress --no-interaction
      - name: Create Database
        run: mkdir -p database && touch database/database.sqlite
      - name: Run Tests
        run: php vendor/bin/phpunit --testdox
        env:
          TEST_DB_ENGINE: ${{ matrix.dbengine }}
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: migration_compat_test
        ports:
          - 3306
